refactor: backend, Dockerfile 수정

diff --git a/apps/backend/Dockerfile b/apps/backend/Dockerfile
--- a/apps/backend/Dockerfile
+++ b/apps/backend/Dockerfile
@@ -5,9 +5,8 @@ WORKDIR /app
 
 COPY package.json pnpm-lock.yaml pnpm-workspace.yaml turbo.json ./
 
+COPY apps/ ./apps/
 COPY packages/ ./packages/
-COPY apps/backend/package.json ./apps/backend/package.json
-COPY apps/backend/ ./apps/backend/
 
 RUN pnpm install --frozen-lockfile
 
@@ -19,25 +18,22 @@ ENV TURBO_TEAM=$TURBO_TEAM
 RUN pnpm turbo run build --filter=@apps/backend
 RUN pnpm turbo run prisma:generate --filter=@apps/backend
 
+RUN mkdir /deploy
+RUN pnpm --filter=@apps/backend deploy /deploy --prod
+
 FROM node:20-alpine AS runner
 
 WORKDIR /app
 ENV NODE_ENV=production
 
-RUN npm install -g pnpm
+COPY --from=builder /deploy .
 
-COPY --from=builder /app/package.json ./package.json
-COPY --from=builder /app/pnpm-workspace.yaml ./pnpm-workspace.yaml
-
-COPY --from=builder /app/pnpm-lock.yaml ./pnpm-lock.yaml
-
-COPY --from=builder /app/apps/backend/dist ./apps/backend/dist/
-COPY --from=builder /app/apps/backend/package.json ./apps/backend/package.json
-
-COPY --from=builder /app/packages ./packages
-
-COPY --from=builder /app/node_modules ./node_modules
+RUN echo "--- Runner: Deployed files structure ---" && ls -R && echo "--- End of structure ---"
+RUN echo "--- Runner: Checking for dotenv in deployed node_modules ---" && \
+    (find ./node_modules -name dotenv -type d -print -exec ls -ld {} \; || echo "dotenv not found in deployed node_modules") && \
+    echo "--- Runner: dotenv check end ---"
+# --- 디버깅 라인 끝 ---
 
 EXPOSE 8000
 
-CMD ["pnpm", "--filter", "@apps/backend", "start:backend"]
+CMD ["node", "dist/app.js"]
